server:
  port: 8080

spring:
  application:
    name: brsm-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/youth_system
    username: postgres
    password: postgres